### ISSUE TITLE
sensitive_constants.dart missing

### ISSUE THREAD

**Issue by simranss** [jyotirmoy-paul/private-room#8]
Maybe I am wrong, but sensitive_constants.dart is not mentioned. If that is not provided for sensitive purposes, can you inform me that what am I supposed to use as filler in place of it?

**Comment by jyotirmoy-paul** [comment]
Hi @simranss basically the file just contains a `const developerKey` with a developer set password as a string. I should have taken a different approach instead of including developerKey in a file and then excluding the file from checking into git.

You can find more about the file here in the README.md section of the project - [read about sensitive_constants.dart]( https://github.com/jyotirmoy-paul/private-room#note)

**Comment by simranss** [comment]
Thank you so much
